### PR TITLE
Make cellxgene-gateway work behind a reverse proxy

### LINKED ISSUE #16: Switch to ProxyFix
Currently we use environment variables to indicate the external protocol and host. These values could also be taken from Host and X-Forwarded-Proto headers.
https://flask.palletsprojects.com/en/0.12.x/deploying/wsgi-standalone/#proxy-setups

### PR DESCRIPTION
**Pull request by grst**
I couldn't make cellxgene_gateway work properly behind a reverse proxy that doesn't point to the root path, e.g. `http://myserver.com/cellxgene_gateway`. 

This PR solves this by
 * switching to consistent use of `url_for` everywhere
 * applying the `ProxyFix` class. 

Closes #16.

### CODE REVIEW

**Comment by grst** [comment]
This works in principle for me now. 

I haven't looked into the tests yet (some of them are failing) and the `ProxyFix` should be make configurable somehow, as it is not recommended to serve the app through `ProxyFix` when it's not actually behind a proxy. Also the `x_proto`, `x_host` and `x_prefix` arguments might depend on the actual use case.

**Comment by ericmjl** [comment]
Tagging @alokito! Thanks @grst for your PR :smile:. Alok knows the codebase better than I do, so I've tagged him for a review.

**Comment by alokito** [comment]
Thanks @grst for the PR. I believe it simplifies a great many things; my "EXTERNAL_HOST" and "EXTERNAL_PROTOCOL" environment variables seem like workarounds for not using the X-forwarded-for headers correctly. I'm going to deploy this branch in my environment to see whether this is really the case, and if so merge it. We could another environment variable to control whether ProxyFix is used.

**Comment by alokito** [comment]
Also seems like we need to set up appropriate application contexts for the unit tests.

**Comment by alokito** [comment]
Hi @grst! Sorry for the long delay but I finally managed to test this against my installation, and figure out what to do with ProxyFix. Please take a look at PR #41, if that works for you I would like to merge that and reject this one.

**Comment by grst** [comment]
Superseded by #41.

**Pull request closed without merging**
